# GoReleaser configuration for WirePusher CLI
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: wirepusher
    main: ./main.go
    binary: wirepusher
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'gitlab.com/wirepusher/cli/cmd.version={{.Version}}'
      - -X 'gitlab.com/wirepusher/cli/cmd.commit={{.ShortCommit}}'
      - -X 'gitlab.com/wirepusher/cli/cmd.date={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # No ARM builds for macOS (Apple Silicon uses arm64)
      - goos: darwin
        goarch: arm
      # Windows typically doesn't need ARM builds
      - goos: windows
        goarch: arm

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - SECURITY.md
      - examples/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

