# GoReleaser configuration for Pincho CLI
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pincho
    main: ./main.go
    binary: pincho
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/Pincho-App/pincho-cli/cmd.version={{.Version}}'
      - -X 'github.com/Pincho-App/pincho-cli/cmd.commit={{.ShortCommit}}'
      - -X 'github.com/Pincho-App/pincho-cli/cmd.date={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # No ARM builds for macOS (Apple Silicon uses arm64)
      - goos: darwin
        goarch: arm
      # Windows typically doesn't need ARM builds
      - goos: windows
        goarch: arm

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md
      - docs/CODE_OF_CONDUCT.md
      - docs/SECURITY.md
      - examples/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: Pincho-App
    name: pincho-cli
  draft: false
  prerelease: auto
  name_template: "Pincho CLI {{.Version}}"
  footer: |
    ## Installation

    ### Download Binary
    Download the appropriate archive for your platform from the assets below.

    ### Verify Checksums
    ```bash
    sha256sum -c checksums.txt
    ```

    ---
    Full documentation: https://github.com/Pincho-App/pincho-cli
