# GoReleaser configuration for WirePusher CLI
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: wirepusher
    main: ./main.go
    binary: wirepusher
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'gitlab.com/wirepusher/cli/cmd.version={{.Version}}'
      - -X 'gitlab.com/wirepusher/cli/cmd.commit={{.ShortCommit}}'
      - -X 'gitlab.com/wirepusher/cli/cmd.date={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # No ARM builds for macOS (Apple Silicon uses arm64)
      - goos: darwin
        goarch: arm
      # Windows typically doesn't need ARM builds
      - goos: windows
        goarch: arm

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - SECURITY.md
      - examples/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: "^feat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "Security"
      regexp: "^security"
      order: 2
    - title: "Other"
      order: 999

release:
  github:
    owner: wirepusher
    name: cli
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  header: |
    ## WirePusher CLI {{ .Tag }}

    Official command-line tool for sending push notifications via WirePusher.

    ### Installation

    Download the appropriate binary for your platform below, extract it, and add it to your PATH.

    For detailed installation instructions, see the [README](https://github.com/wirepusher/cli#installation).

  footer: |
    ### Verifying Downloads

    All binaries are checksummed. Verify your download:

    ```bash
    # Linux/macOS
    sha256sum -c checksums.txt

    # Windows PowerShell
    Get-FileHash wirepusher.exe -Algorithm SHA256
    ```

    ### Documentation

    - [Getting Started Guide](https://github.com/wirepusher/cli#quick-start)
    - [API Documentation](https://wirepusher.com/docs)
    - [Examples](https://github.com/wirepusher/cli/tree/main/examples)

    ### Support

    - Report issues: https://github.com/wirepusher/cli/issues
    - Email: support@wirepusher.com

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Homebrew tap (optional - can be added later)
# brews:
#   - repository:
#       owner: wirepusher
#       name: homebrew-tap
#     homepage: https://wirepusher.com
#     description: Official CLI tool for WirePusher push notifications
#     license: MIT
#     install: |
#       bin.install "wirepusher"
