# GoReleaser configuration for WirePusher CLI
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: wirepusher
    main: ./main.go
    binary: wirepusher
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'gitlab.com/wirepusher/cli/cmd.version={{.Version}}'
      - -X 'gitlab.com/wirepusher/cli/cmd.commit={{.ShortCommit}}'
      - -X 'gitlab.com/wirepusher/cli/cmd.date={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # No ARM builds for macOS (Apple Silicon uses arm64)
      - goos: darwin
        goarch: arm
      # Windows typically doesn't need ARM builds
      - goos: windows
        goarch: arm

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md
      - docs/CODE_OF_CONDUCT.md
      - docs/SECURITY.md
      - examples/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# GitLab releases configuration
gitlab_urls:
  api: https://gitlab.com/api/v4/
  download: https://gitlab.com
  skip_tls_verify: false
  use_package_registry: false
  use_job_token: false

release:
  gitlab:
    owner: wirepusher
    name: wirepusher-cli
  draft: false
  prerelease: auto
  name_template: "WirePusher CLI {{.Version}}"
  footer: |
    ## Installation

    ### Download Binary
    Download the appropriate archive for your platform from the assets below.

    ### Verify Checksums
    ```bash
    sha256sum -c checksums.txt
    ```

    ---
    Full documentation: https://gitlab.com/wirepusher/wirepusher-cli

